# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea4cebe1a87d9d87d4970f44b61827af263ab1f3f81571395ab8e70690cdca8c86db77fedd8cd16a8b6698e6583383081de85d729183030a3017bf9928bb2ec4

test:
  secret_key_base: 271da261883270f9917dc4e3940844f919faf2e0b4ad9f260f60298c8c32735205901d7d8a3fa12a3bd70f8873d780942ec9aa8df6d8739cffe6d3a39f2676ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
